version: '1.0'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=saveFiles
    networks:
      - save-network
    ports:
      - "27017:27017"
    restart: always

  app:
    depends_on:
      - mongodb
    image: frankester/savefiles:savefiles
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - save-network
    environment:
      - SPRING.DATA.MONGODB.URI=mongodb://mongodb:27017
      - SPRING.DATA.MONGODB.DATABASE=saveFiles
      - AWS.ACCESSKEYID=ACCESS_KEY_ID
      - AWS.SECRETACCESSKEY=SECRET_ACCESS_KEY
      - AWS.REGION=us-east-1
      - AWS.BUCKETNAME=BUCKET_NAME

networks:
  save-network: